---
- name: update all packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Copy sshd_config file
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    backup: yes

- name : Change ssh port to 6520
  lininfile:
    path: /etc/ssh/sshd_config
    regexp: "Port 22"
    line: "Port 6522"
    state: present

- name: Restart sshd
  service: 
    name: sshd
    state: restarted

- name: Create logrotate config file
  copy:
    src: /etc/logrotate.conf
    dest: /etc/logrorate.d/ 
    mode: 0600

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    - "{{ intallpackages }}"

- name: Add users with sudo permission
  user:
    name: ansible-user
    groups: sudo

- name: Add users
  user: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ users }}"
 
- name: Change file permission for /etc/shadow
  file:
    path: /etc/shadow
    state: file
    mode: "0400"
     
      
     
      
      
     
# tasks file for common
